name: Preview - Deploy & Test

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: preview-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Detect targets from spec
  detect-targets:
    name: Detect Build Targets
    runs-on: ubuntu-latest
    outputs:
      has-web: ${{ steps.read-spec.outputs.has-web }}
      has-backend: ${{ steps.read-spec.outputs.has-backend }}
      project-name: ${{ steps.read-spec.outputs.project-name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read BuildSpec
        id: read-spec
        run: |
          if [ -f "workspace/spec.json" ]; then
            SPEC_FILE="workspace/spec.json"
          elif [ -f "spec.json" ]; then
            SPEC_FILE="spec.json"
          else
            echo "has-web=true" >> $GITHUB_OUTPUT
            echo "has-backend=false" >> $GITHUB_OUTPUT
            echo "project-name=unknown" >> $GITHUB_OUTPUT
            exit 0
          fi

          TARGETS=$(cat $SPEC_FILE | jq -r '.targets | @json')
          PROJECT_NAME=$(cat $SPEC_FILE | jq -r '.name // "unknown"')

          echo "project-name=$PROJECT_NAME" >> $GITHUB_OUTPUT

          if echo "$TARGETS" | jq -e 'index("web")' > /dev/null; then
            echo "has-web=true" >> $GITHUB_OUTPUT
          else
            echo "has-web=false" >> $GITHUB_OUTPUT
          fi

          if echo "$TARGETS" | jq -e 'index("backend")' > /dev/null; then
            echo "has-backend=true" >> $GITHUB_OUTPUT
          else
            echo "has-backend=false" >> $GITHUB_OUTPUT
          fi

  deploy-and-test:
    runs-on: ubuntu-latest
    needs: detect-targets
    if: needs.detect-targets.outputs.has-web == 'true'
    timeout-minutes: 15
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            apps/web/package-lock.json

      - name: Install root dependencies
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm i --no-audit --no-fund; fi
          npm i --no-save @playwright/test yaml fs-extra wait-on

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Install and build Next.js app
        working-directory: apps/web
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm i --no-audit --no-fund; fi
          npm run build

      - name: Deploy to Vercel Preview
        id: deploy
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        working-directory: apps/web
        run: |
          npm i -g vercel
          PREVIEW_URL=$(vercel deploy --token=$VERCEL_TOKEN --yes 2>&1 | grep -oP 'https://[^\s]+\.vercel\.app' | head -1)
          echo "preview_url=$PREVIEW_URL" >> $GITHUB_OUTPUT
          echo "Preview URL: $PREVIEW_URL"

      - name: Wait for deployment
        run: |
          echo "Waiting for ${{ steps.deploy.outputs.preview_url }} to be ready..."
          npx wait-on ${{ steps.deploy.outputs.preview_url }} --timeout 60000

      - name: Run UI smoke tests
        id: smoke
        env:
          WORKSPACE: ${{ github.workspace }}
        run: |
          set +e
          node tools/ui-runner-cli.js checklists/auth.yaml ${{ steps.deploy.outputs.preview_url }}
          SMOKE_EXIT=$?
          echo "exit_code=$SMOKE_EXIT" >> $GITHUB_OUTPUT

          # Parse results
          RESULT_FILE=$(find artifacts/ui -name "result.json" -type f | sort -r | head -1)
          if [ -f "$RESULT_FILE" ]; then
            PASSED=$(jq -r '.checkpointsPassed' "$RESULT_FILE")
            TOTAL=$(jq -r '.checkpointsTotal' "$RESULT_FILE")
            SUCCESS=$(jq -r '.success' "$RESULT_FILE")
            echo "passed=$PASSED" >> $GITHUB_OUTPUT
            echo "total=$TOTAL" >> $GITHUB_OUTPUT
            echo "success=$SUCCESS" >> $GITHUB_OUTPUT
          else
            echo "passed=0" >> $GITHUB_OUTPUT
            echo "total=0" >> $GITHUB_OUTPUT
            echo "success=false" >> $GITHUB_OUTPUT
          fi

          exit $SMOKE_EXIT

      - name: Upload UI screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: preview-screenshots-pr-${{ github.event.pull_request.number }}
          path: artifacts/ui
          if-no-files-found: warn

      - name: Post PR comment
        if: always()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const passed = '${{ steps.smoke.outputs.passed }}';
            const total = '${{ steps.smoke.outputs.total }}';
            const success = '${{ steps.smoke.outputs.success }}' === 'true';
            const previewUrl = '${{ steps.deploy.outputs.preview_url }}';
            const runId = '${{ github.run_id }}';
            const prNumber = context.issue.number;
            const projectName = '${{ needs.detect-targets.outputs.project-name }}';

            const statusIcon = success ? '✅' : '❌';
            const statusText = success ? 'PASSED' : 'FAILED';

            // Calculate pass rate percentage
            const passRate = total > 0 ? Math.round((passed / total) * 100) : 0;

            const body = `## ${statusIcon} Preview Deployment ${statusText}

            **Project:** ${projectName}
            **Preview URL:** [${previewUrl}](${previewUrl})

            ### 🧪 Test Results

            #### UI Smoke Tests
            - **Status:** ${statusIcon} ${statusText}
            - **Checkpoints:** ${passed}/${total} passed (${passRate}%)
            ${passed > 0 ? '- ✅ ' + passed + ' checkpoints verified successfully' : ''}
            ${total - passed > 0 ? '- ❌ ' + (total - passed) + ' checkpoints failed' : ''}

            ### 📸 Artifacts
            - [View Screenshots & Test Results](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${runId})
            - [Download Artifacts](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${runId}#artifacts)

            ### 🔍 Quick Links
            - [Preview Deployment](${previewUrl})
            - [CI Workflow Run](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${runId})
            - [Commit Details](https://github.com/${context.repo.owner}/${context.repo.repo}/commit/${context.sha})

            <details>
            <summary>📋 Test Details</summary>

            \`\`\`
            Workflow:      Preview - Deploy & Test
            Run ID:        ${runId}
            PR:            #${prNumber}
            Commit:        ${context.sha.substring(0, 7)}
            Project:       ${projectName}
            Test Suite:    UI Smoke Tests (Playwright)
            Pass Rate:     ${passRate}%
            \`\`\`
            </details>

            <details>
            <summary>💡 Next Steps</summary>

            ${success ?
              '✅ All tests passed! Your changes are ready for review.' :
              '❌ Some tests failed. Please review the screenshots and logs above.'}

            - Review the [test artifacts](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${runId})
            - Check the [preview deployment](${previewUrl})
            ${!success ? '- Fix failing tests and push updates to re-run verification' : ''}
            </details>

            ---
            🤖 *Automated preview deployment powered by [ORK](https://github.com/anthropics/ork) · Target-aware CI*`;

            // Find existing comment
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
            });

            const botComment = comments.find(comment =>
              comment.user.type === 'Bot' &&
              comment.body.includes('Preview Deployment')
            );

            if (botComment) {
              // Update existing comment
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: body
              });
            } else {
              // Create new comment
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: body
              });
            }
